### ISSUE TITLE
Says OpenSSL isn't installed when it is

### ISSUE THREAD

**Issue by djsawicko** [colonelwatch/nonceMiner#26]
![PXL_20210911_111629817.jpg](https://user-images.githubusercontent.com/75716744/132946053-0ce42969-092e-4920-a4bf-07e81131feae.jpg)

Yes it is the non-light version, i tried msi installer in /bin directory msi installer in windows exe installer in /bin and exe installer in Windows directory, i also tried copying the install of openSSL to nonceminers folder, also didn't help...

**Comment by djsawicko** [comment]
Sooooo, there is a new version of OpenSSL, install 1.1 and nothing else

**Comment by colonelwatch** [comment]
Oh, OpenSSL finally released a 3.0 binary now? I totally wasn't aware of that. I should check if nonceMiner can upgrade, or else I need to add a disclaimer. Thanks for checking in, really. I didn't have the time lately to get the bottom of this.

**Comment by colonelwatch** [comment]
Okay, I did some quick testing, and I don't think upgrading to OpenSSL 3.0 is a good idea for nonceMiner. Here's why I think so:

duino-coin is unique in that its DUCO-S1 algorithm actually involves very little hashing—I've measured it before. Because the algorithm calls for very small inputs to be hashed (about 40-50 bytes, not even one full block), the CPU spends more time doing other things than actual hashing. This is true for both the official miner and nonceMiner, just that nonceMiner has actually has optimized the "other things" and left the hashing to third-party libraries.

OpenSSL decided to depreciate low-level hashing functions, preferring high-level functions instead. For large inputs (where hashing is most of the CPU load), this isn't a problem. However, the overhead of this high-level stuff *is* a problem for small inputs like in DUCO-S1, giving me roughly a 50% performance loss. For that reason, I'm going to specify that users need to install OpenSSL 1.1.1, not OpenSSL 3.0.
