### ISSUE TITLE
Segmentation fault on Raspberry Pi

### ISSUE THREAD

**Issue by Ianmcmill** [colonelwatch/nonceMiner#8]
I've tried this on a Rasperry pi zero.
The miner quits after running the compiled binary.
No error messages

`pi@sideframe:~/nonceMiner $ make nonceMiner`

> mkdir bin
> gcc src/nonceMiner.c src/mine_DUCO_S1.c -O3 -Wall -o bin/nonceMiner -lcrypto -lpthread

`pi@sideframe:~/nonceMiner $ ./bin/nonceMiner`

> Initializing nonceMiner v1.3.1...
> Enter username: xxxxxx
> Enter identifier ("None" for no identifier): PiZeroNonce
> Enter # of threads: 1
> Starting threads...
> Segmentation fault

-> quit

I ran it a second time and got one hash result but then a segmentation fault

```
20:37:33  Hashrate: 0.00 MH/s, Accepted 0, Rejected 0
Segmentation fault
```

**Comment by colonelwatch** [comment]
I don't have a Raspberry Pi Zero myself to reproduce this issue, so I can only guess that it failed to allocate enough memory for one of my lookup tables. This can be a couple hundred megabytes, and the Zero has only 512 MB.

Let me write in some checks, and it will ditch the lookup table if any of those checks fail for now.

**Comment by GilDev** [comment]
Same issue on Raspberry Pi 4, from 1 to 16 threads.

**Comment by colonelwatch** [comment]
> Same issue on Raspberry Pi 4, from 1 to 16 threads.

Thanks for letting me know that its also a problem on a regular Raspberry Pi, I *do* have a Pi 3 Model B, and I can reproduce the segfault now even with that commit I put in. As far as I can tell then, its a deeper problem than just RAM size.

**Comment by colonelwatch** [comment]
Some progress on the issue. Responding to issue #7, I decided to default to requesting the EXTREME difficulty because desktop computers would be too fast then get rejected. In theory, the EXTREME diff shouldn't be a problem on a Raspberry Pi, but I changed it back to NET difficulty and ran nonceMiner_minimal...

```
pi@raspberrypi:~/duinocoin/nonceMiner $ ./bin/nonceMiner_minimal
Rejected share 16186012 Difficulty 280364
Accepted share 30021524 Difficulty 388906
Accepted share 6160580 Difficulty 296734
Segmentation fault
```

and I managed to get some accepted shares before it segfaulted again. Modifying it to print out the jobstring gives me

```
pi@raspberrypi:~/duinocoin/nonceMiner $ ./bin/nonceMiner_minimal
50425db3a5f272e9563c2c03424186ef872f40ac,cf2ce3e5775b232fc5806cf967d7982127fcf668,281359
Rejected share 14792436 Difficulty 281359
e6f9b01b2ab5c1c2acace6bae090094334f816c1,af7a0e7eb6b7047a9bfb3f5f5aca6f74a28a3d5e,410577
Accepted share 14891778 Difficulty 410577
e4f305e545416f5152c55973aea84c1225c31db4,4c8ac8ff524d57d42d7bceaa4a5d66a9ac8e2f6b,569114
Segmentation fault
```

The segfault seems to happen as the difficulty is ramping up, and the EXTREME difficulty *starts* it too high.

**Comment by colonelwatch** [comment]
I've started to nail down where the segfault happens. I'm a complete beginner with the gdb debugger here, but what I've nailed down is:

- it's in the hashing loop,
- it segfaults relatively quickly (within 100000 hashes),  
- it only happens if the maximum is too large (the maximum *can* be larger than 100000),
- it takes place during an assignment

(Edit: I removed the gdb log because I managed to decipher it myself. However, you can still see log if you click the "edited" tab.)

**Comment by colonelwatch** [comment]
Finally, I found the cause of the segfault, and best I explain it with an example.

1. nonceMiner receives a job of difficulty `7654321`.
2. It mallocs a cache of size `7654321/100`, or `76543`
3. It hashes up to a nonce of `765431` 
4. It erroneously decides to access the cached context for `765431/10`, or `76543` (see [this old, offending line](https://github.com/colonelwatch/nonceMiner/blob/3ab266fec35550d8d186e52c6a10597349924c8c/src/mine_DUCO_S1.c#L94))
5. It accesses the cache with an index of `76543` which, in fact, is outside the cache by just 1
6. Many systems let this happen (probably returning garbage data), but the Raspberry Pi will segfault.

How this flew under the radar for so long? See steps 5-6, and the odds of `765431` or a similar case being part of the right answer is very low. As to why this doesn't happen when the maximum is smaller? I'm not sure, to be honest, and I'll leave that as an open question.

**Comment by colonelwatch** [comment]
By the way, 94008dd does not work at all because Linux overcommits memory. In theory, each thread could malloc 900MB in a 1GB RAM system, then the whole process gets killed for out-of-memory. I'll revert it.

**Comment by GilDev** [comment]
Good job finding that! Interesting bug.
