### ISSUE TITLE
List of small issues I've run into

### ISSUE THREAD

**Issue by robtech21** [colonelwatch/nonceMiner#9]
This is a great miner. I've been using it with my "Le Potato" SBC (4 threads) and it seems to be increasing my earnings much faster compared to the official Python miner. However, I have run into a few issues I wanted to make you aware of:

* An error on the [mining dashboard](https://lulaschkas.github.io/duco-mining-dashboard/) ("Miner with Rigname: LePotato Full Software name: nonceMiner v1.4.0 is probably using an old Version. Please upgrade.")
* ~~Can't add spaces to the identifier or otherwise the program will fail to run.~~
* Random thread disconnects (ping timeout) but they seem to reconnect

**Comment by colonelwatch** [comment]
Glad to hear it, and thanks for letting me know. I'll try to look into the second and third issues soon.

Regarding the first issue, I'd think that, at the very least, there doesn't need to be that kind of warning for third-party software. I'll reference this issue when I go open one for the monitor.

**Comment by colonelwatch** [comment]
I'm starting suspect the occasional disconnections are server-side because I also get connection problems with the official miner. Can anyone else confirm or deny this? The timeouts for the official miner are 30 seconds vs 16 seconds over here, so the official miner may take longer to error out or error out less frequently. (Really though, both 30 and 16 are too long in my opinion, but the server really does take that long to respond sometimes. Is it over burdened?)

If it really is server-side, then there's nothing I can do about it: my miner just reports the same problem a little differently. That said, I do also need to fix the failure to recover problem, #10.

**Comment by robtech21** [comment]
> I'm starting suspect the occasional disconnections are server-side because I also get connection problems with the official miner. Can anyone else confirm or deny this? The timeouts for the official miner are 30 seconds vs 16 seconds over here, so the official miner may take longer to error out or error out less frequently. (Really though, both 30 and 16 are too long in my opinion, but the server really does take that long to respond sometimes. Is it over burdened?)
> 
> If it really is server-side, then there's nothing I can do about it: my miner just reports the same problem a little differently. That said, I do also need to fix the failure to recover problem, #10.

I get connection problems with the official miner, just less of them I think.

**Comment by colonelwatch** [comment]
Okay, I think that's everything for this issue, then. The author of the mining dashboard says he's fixed it, the identifier can have spaces now, and the server disconnects appear to be out of my control. Has anyone reported that last thing in the duino-coin repo? Anyway, I'll close this issue and make a new release.
